stages:
  - deploy

deploy-backend:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - echo "$DEPLOY_KEY" > deploy_key
    - chmod 600 deploy_key
    - ssh -o StrictHostKeyChecking=no -i deploy_key ubuntu@52.193.216.8 "
        cd /home/ubuntu/Stock_Pulse &&
        git pull &&
        docker compose down &&
        docker compose up -d --build
      "
  only:
    - main
